# Generated by Django 2.0.5 on 2019-02-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceToolCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_wallet', models.DateTimeField(default=None, null=True)),
                ('last_update_notifs', models.DateTimeField(default=None, null=True)),
                ('last_update_assets', models.DateTimeField(default=None, null=True)),
                ('last_update_structs', models.DateTimeField(default=None, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter')),
            ],
            options={
                'permissions': (('access_alliance_tools', 'Can access alliance_tools'), ('admin_alliance_tools', 'Can add tokens to alliance tools')),
            },
        ),
        migrations.CreateModel(
            name='CorpAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_copy', models.NullBooleanField(default=None)),
                ('singleton', models.BooleanField()),
                ('item_id', models.BigIntegerField(unique=True)),
                ('location_flag', models.CharField(max_length=50)),
                ('location_id', models.BigIntegerField()),
                ('location_type', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_corp', to='eveonline.EveCorporationInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporationWalletDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('division', models.IntegerField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_corp_division', to='eveonline.EveCorporationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CorporationWalletJournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('context_id', models.BigIntegerField(default=None, null=True)),
                ('context_id_type', models.CharField(choices=[('structure_id', 'structure_id'), ('station_id', 'station_id'), ('market_transaction_id', 'market_transaction_id'), ('character_id', 'character_id'), ('corporation_id', 'corporation_id'), ('alliance_id', 'alliance_id'), ('eve_system', 'eve_system'), ('industry_job_id', 'industry_job_id'), ('contract_id', 'contract_id'), ('planet_id', 'planet_id'), ('system_id', 'system_id'), ('type_id', 'type_id')], default=None, max_length=30, null=True)),
                ('description', models.CharField(max_length=500)),
                ('first_party_id', models.IntegerField(default=None, null=True)),
                ('entry_id', models.BigIntegerField()),
                ('reason', models.CharField(default=None, max_length=500, null=True)),
                ('ref_type', models.CharField(max_length=72)),
                ('second_party_id', models.IntegerField(default=None, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('tax_reciever_id', models.IntegerField(default=None, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.CorporationWalletDivision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.BigIntegerField()),
                ('sender_id', models.IntegerField()),
                ('sender_type', models.CharField(choices=[('character', 'character'), ('corporation', 'corporation'), ('alliance', 'alliance'), ('faction', 'faction'), ('other', 'other')], max_length=15)),
                ('notification_text', models.TextField(default=None, null=True)),
                ('timestamp', models.DateTimeField()),
                ('notification_type', models.CharField(max_length=50)),
                ('is_read', models.NullBooleanField(default=None)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.AllianceToolCharacter')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_expires', models.DateTimeField(default=None, null=True)),
                ('next_reinforce_apply', models.DateTimeField(default=None, null=True)),
                ('next_reinforce_weekday', models.IntegerField(default=None, null=True)),
                ('profile_id', models.IntegerField()),
                ('reinforce_hour', models.IntegerField()),
                ('reinforce_weekday', models.IntegerField()),
                ('state', models.CharField(choices=[('anchor_vulnerable', 'anchor_vulnerable'), ('anchoring', 'anchoring'), ('armor_reinforce', 'armor_reinforce'), ('armor_vulnerable', 'armor_vulnerable'), ('fitting_invulnerable', 'fitting_invulnerable'), ('hull_reinforce', 'hull_reinforce'), ('hull_vulnerable', 'hull_vulnerable'), ('online_deprecated', 'online_deprecated'), ('onlining_vulnerable', 'onlining_vulnerable'), ('shield_vulnerable', 'shield_vulnerable'), ('unanchored', 'unanchored'), ('unknown', 'unknown')], max_length=25)),
                ('state_timer_end', models.DateTimeField(default=None, null=True)),
                ('state_timer_start', models.DateTimeField(default=None, null=True)),
                ('structure_id', models.BigIntegerField()),
                ('system_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('unanchors_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(choices=[('anchor_vulnerable', 'anchor_vulnerable'), ('anchoring', 'anchoring'), ('armor_reinforce', 'armor_reinforce'), ('armor_vulnerable', 'armor_vulnerable'), ('fitting_invulnerable', 'fitting_invulnerable'), ('hull_reinforce', 'hull_reinforce'), ('hull_vulnerable', 'hull_vulnerable'), ('online_deprecated', 'online_deprecated'), ('onlining_vulnerable', 'onlining_vulnerable'), ('shield_vulnerable', 'shield_vulnerable'), ('unanchored', 'unanchored'), ('unknown', 'unknown')], max_length=25)),
                ('ozone_level', models.IntegerField(default=None, null=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_structure', to='eveonline.EveCorporationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StructureService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('cleanup', 'cleanup')], max_length=8)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.Structure')),
            ],
        ),
    ]
