# Generated by Django 2.0.5 on 2019-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeName',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('type_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
