# Generated by Django 2.0.5 on 2019-02-04 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0002_itemname_typename'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporationwalletjournalentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
