# Generated by Django 2.0.5 on 2019-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0003_corporationwalletjournalentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='reinforce_weekday',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
