# Generated by Django 2.0.5 on 2019-02-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0004_auto_20190204_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='next_update_assets',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='next_update_notifs',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='next_update_structs',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='next_update_wallet',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
