# Generated by Django 2.0.5 on 2019-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0005_auto_20190205_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(choices=[('anchor_vulnerable', 'anchor_vulnerable'), ('anchoring', 'anchoring'), ('armor_reinforce', 'armor_reinforce'), ('armor_vulnerable', 'armor_vulnerable'), ('fitting_invulnerable', 'fitting_invulnerable'), ('hull_reinforce', 'hull_reinforce'), ('hull_vulnerable', 'hull_vulnerable'), ('online_deprecated', 'online_deprecated'), ('onlining_vulnerable', 'onlining_vulnerable'), ('shield_vulnerable', 'shield_vulnerable'), ('unanchored', 'unanchored'), ('unknown', 'unknown')], max_length=150),
        ),
    ]
