# Generated by Django 2.0.5 on 2019-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0006_auto_20190206_0928'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='corporationwalletjournalentry',
            index=models.Index(fields=['entry_id'], name='alliancetoo_entry_i_57567f_idx'),
        ),
        migrations.AddIndex(
            model_name='corporationwalletjournalentry',
            index=models.Index(fields=['date'], name='alliancetoo_date_bea78a_idx'),
        ),
    ]
