# Generated by Django 2.0.5 on 2019-02-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0008_bridgeozonelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeozonelevel',
            name='quantity',
            field=models.BigIntegerField(),
        ),
        migrations.AddField(
            model_name='bridgeozonelevel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
