# Generated by Django 2.0.5 on 2019-02-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0009_auto_20190209_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpasset',
            name='item_id',
            field=models.BigIntegerField(),
        ),
    ]
