# Generated by Django 2.0.5 on 2019-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0010_auto_20190210_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgeozonelevel',
            name='used',
            field=models.BigIntegerField(default=0),
        ),
    ]
