# Generated by Django 2.0.5 on 2019-02-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0011_bridgeozonelevel_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSolarSystem',
            fields=[
                ('regionID', models.BigIntegerField()),
                ('regionName', models.CharField(default=None, max_length=500, null=True)),
                ('constellationID', models.BigIntegerField()),
                ('constellationName', models.CharField(default=None, max_length=500, null=True)),
                ('solarSystemID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('solarSystemName', models.CharField(max_length=500)),
                ('x', models.DecimalField(decimal_places=5, max_digits=30)),
                ('y', models.DecimalField(decimal_places=5, max_digits=30)),
                ('z', models.DecimalField(decimal_places=5, max_digits=30)),
                ('xMin', models.DecimalField(decimal_places=5, max_digits=30)),
                ('xMax', models.DecimalField(decimal_places=5, max_digits=30)),
                ('yMin', models.DecimalField(decimal_places=5, max_digits=30)),
                ('yMax', models.DecimalField(decimal_places=5, max_digits=30)),
                ('zMin', models.DecimalField(decimal_places=5, max_digits=30)),
                ('zMax', models.DecimalField(decimal_places=5, max_digits=30)),
                ('luminosity', models.DecimalField(decimal_places=12, max_digits=13)),
                ('border', models.IntegerField(default=None, null=True)),
                ('fringe', models.IntegerField(default=None, null=True)),
                ('corridor', models.IntegerField(default=None, null=True)),
                ('hub', models.IntegerField(default=None, null=True)),
                ('international', models.IntegerField(default=None, null=True)),
                ('regional', models.IntegerField(default=None, null=True)),
                ('security', models.DecimalField(decimal_places=10, max_digits=15)),
                ('radius', models.DecimalField(decimal_places=5, max_digits=30)),
                ('sunTypeID', models.BigIntegerField()),
                ('securityClass', models.CharField(max_length=3)),
            ],
        ),
    ]
