# Generated by Django 2.0.5 on 2019-02-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0012_mapsolarsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='securityClass',
            field=models.CharField(max_length=5),
        ),
    ]
