# Generated by Django 2.0.5 on 2019-02-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0013_auto_20190212_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='luminosity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='radius',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='security',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='xMax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='xMin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='yMax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='yMin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='z',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='zMax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mapsolarsystem',
            name='zMin',
            field=models.FloatField(),
        ),
    ]
