# Generated by Django 2.0.5 on 2019-02-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0015_auto_20190212_0939'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapsolarsystem',
            index=models.Index(fields=['regionID'], name='alliancetoo_regionI_2f0d57_idx'),
        ),
        migrations.AddIndex(
            model_name='mapsolarsystem',
            index=models.Index(fields=['solarSystemID'], name='alliancetoo_solarSy_5f9099_idx'),
        ),
    ]
