# Generated by Django 2.0.5 on 2019-02-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0016_auto_20190212_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alliancetoolcharacter',
            options={'permissions': (('access_alliance_tools', 'Can access alliance_tools'), ('access_alliance_tools_structures', 'Can access structures'), ('access_alliance_tools_structure_fittings', 'Can access structure fittings'), ('admin_alliance_tools', 'Can add tokens to alliance tools'))},
        ),
        migrations.RemoveField(
            model_name='structure',
            name='ozone_level',
        ),
    ]
