# Generated by Django 2.0.5 on 2019-02-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0018_structure_system_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='type_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.TypeName'),
        ),
    ]
