# Generated by Django 2.0.5 on 2019-03-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0022_auto_20190227_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_webhook', models.TextField()),
                ('structure_ping', models.BooleanField(default=True)),
                ('entosis_ping', models.BooleanField(default=True)),
                ('fuel_ping', models.BooleanField(default=False)),
                ('corporation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCorporationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('time', models.DateTimeField()),
                ('catagory', models.TextField()),
                ('notification_id', models.BigIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='alliancetoolcharacter',
            options={'permissions': (('access_alliance_tools', 'Can access alliance_tools'), ('access_alliance_tools_structures', 'Can access structures'), ('access_alliance_tools_structure_fittings', 'Can access structure fittings'), ('access_alliance_tools_structures_renter', 'Can access renter structures'), ('access_alliance_tools_structure_fittings_renter', 'Can access renter structure fittings'), ('admin_alliance_tools', 'Can add tokens to alliance tools'))},
        ),
    ]
