# Generated by Django 2.1.7 on 2019-04-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0025_groupreqwebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.BigIntegerField()),
                ('system_id', models.IntegerField()),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('standing_level', models.CharField(choices=[('bad', 'bad'), ('excellent', 'excellent'), ('good', 'good'), ('neutral', 'neutral'), ('terrible', 'terrible')], default=None, max_length=15, null=True)),
                ('terrible_standing_tax_rate', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('neutral_standing_tax_rate', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('good_standing_tax_rate', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('excellent_standing_tax_rate', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('bad_standing_tax_rate', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('corporation_tax_rate', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('alliance_tax_rate', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True)),
                ('reinforce_exit_start', models.IntegerField()),
                ('reinforce_exit_end', models.IntegerField()),
                ('allow_alliance_access', models.BooleanField()),
                ('allow_access_with_standings', models.BooleanField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
            ],
        ),
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='last_update_pocos',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='next_update_pocos',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
