# Generated by Django 2.1.7 on 2019-04-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0026_auto_20190409_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alliancetoolcharacter',
            options={'permissions': (('access_alliance_tools', 'Can access alliance_tools'), ('access_alliance_tools_structures', 'Can access structures'), ('access_alliance_tools_structure_fittings', 'Can access structure fittings'), ('access_alliance_tools_structures_renter', 'Can access renter structures'), ('access_alliance_tools_structure_fittings_renter', 'Can access renter structure fittings'), ('admin_alliance_tools', 'Can add tokens to alliance tools'), ('corp_level_alliance_tools', 'Can add corporate structure tokens to alliance tools '))},
        ),
    ]
