# Generated by Django 2.1.7 on 2019-05-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0028_poco_solar_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocoCelestial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.BigIntegerField()),
                ('celestial_name', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='poco',
            name='closest_celestial',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.PocoCelestial'),
        ),
    ]
