# Generated by Django 2.1.7 on 2019-05-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0029_auto_20190525_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationalert',
            name='transfer_ping',
            field=models.BooleanField(default=False),
        ),
    ]
