# Generated by Django 2.2.2 on 2019-06-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0030_notificationalert_transfer_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='AssetLogConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=500)),
                ('corporation_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCorporationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('corporation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCorporationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.BigIntegerField(unique=True)),
                ('system_id', models.IntegerField(default=None, null=True)),
                ('type_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=150)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('system_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.MapSolarSystem')),
                ('type_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.TypeName')),
            ],
        ),
    ]
