# Generated by Django 2.2.2 on 2019-06-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0031_auto_20190620_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlocation',
            name='corporation',
        ),
    ]
