# Generated by Django 2.2.2 on 2019-06-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0032_remove_assetlocation_corporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='last_update_moons',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='next_update_moons',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MoonExtractEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('decay_time', models.DateTimeField()),
                ('moon_id', models.IntegerField()),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('moon_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.ItemName')),
                ('notification', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.Notification')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.Structure')),
            ],
            options={
                'unique_together': {('arrival_time', 'moon_id')},
            },
        ),
    ]
