# Generated by Django 2.2.2 on 2019-07-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0033_auto_20190625_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='last_update_moon_obs',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alliancetoolcharacter',
            name='next_update_moon_obs',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='MoonWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_webhook', models.TextField()),
                ('ping_day', models.IntegerField(default=6)),
                ('ping_hour', models.IntegerField(default=13)),
                ('days_forward', models.IntegerField(default=4)),
                ('system_filter', models.CharField(max_length=50)),
                ('constellation_filter', models.CharField(max_length=50)),
                ('region_filter', models.CharField(max_length=50)),
                ('last_ping', models.DateTimeField(default=None, null=True)),
                ('last_ping_details', models.TextField()),
                ('corporation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCorporationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MiningObserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField()),
                ('observer_id', models.BigIntegerField()),
                ('observer_type', models.CharField(choices=[('structure', 'structure')], max_length=10)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_corp', to='eveonline.EveCorporationInfo')),
                ('structure', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='MiningObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('quantity', models.BigIntegerField()),
                ('recorded_corporation_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.MiningObserver')),
            ],
        ),
    ]
