# Generated by Django 2.2.2 on 2019-07-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0035_miningobservation_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miningobservation',
            name='observer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.MiningObserver'),
        ),
        migrations.CreateModel(
            name='RentedMoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_corp', models.CharField(max_length=500)),
                ('Moon', models.CharField(max_length=500)),
                ('renter_contact', models.CharField(max_length=500)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('observer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.MiningObserver')),
            ],
        ),
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max', models.DecimalField(decimal_places=2, max_digits=20)),
                ('avg', models.DecimalField(decimal_places=2, max_digits=20)),
                ('move', models.BigIntegerField()),
                ('orders', models.IntegerField()),
                ('region_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alliancetools.ItemName')),
            ],
        ),
    ]
