# Generated by Django 2.2.2 on 2019-07-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0037_auto_20190719_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alliancetools.TypeName')),
            ],
        ),
    ]
