# Generated by Django 2.2.2 on 2019-07-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0038_oreprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptor_id', models.IntegerField()),
                ('assignee_id', models.IntegerField()),
                ('availability', models.CharField(choices=[('public', 'public'), ('personal', 'personal'), ('corporation', 'corporation'), ('alliance', 'alliance')], max_length=11)),
                ('buyout', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('collateral', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('contract_id', models.IntegerField()),
                ('date_accepted', models.DateTimeField(default=None, null=True)),
                ('date_completed', models.DateTimeField(default=None, null=True)),
                ('date_expired', models.DateTimeField()),
                ('date_issued', models.DateTimeField()),
                ('days_to_complete', models.IntegerField(default=None, null=True)),
                ('end_location_id', models.BigIntegerField(default=None, null=True)),
                ('for_corporation', models.BooleanField()),
                ('issuer_corporation_id', models.IntegerField()),
                ('issuer_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=20)),
                ('start_location_id', models.BigIntegerField(default=None, null=True)),
                ('status', models.CharField(choices=[('outstanding', 'outstanding'), ('in_progress', 'in_progress'), ('finished_issuer', 'finished_issuer'), ('finished_contractor', 'finished_contractor'), ('finished', 'finished'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('failed', 'failed'), ('deleted', 'deleted'), ('reversed', 'reversed')], max_length=11)),
                ('title', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('unknown', 'unknown'), ('item_exchange', 'item_exchange'), ('auction', 'auction'), ('courier', 'courier'), ('loan', 'loan')], max_length=18)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicContractSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(unique=True)),
                ('region', models.CharField(max_length=50)),
                ('last_update_moon_obs', models.DateTimeField(blank=True, default=None, null=True)),
                ('next_update_wallet', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicContractItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField()),
                ('singleton', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('raw_quantity', models.IntegerField(default=None, null=True)),
                ('record_id', models.BigIntegerField()),
                ('type_id', models.IntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.PublicContract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publiccontract',
            name='pub_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.PublicContractSearch'),
        ),
    ]
