# Generated by Django 2.2.2 on 2019-07-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0039_auto_20190727_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccontract',
            name='acceptor_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='date_expired',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
