# Generated by Django 2.2.2 on 2019-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0040_auto_20190727_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccontract',
            name='assignee_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
