# Generated by Django 2.2.2 on 2019-07-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0041_auto_20190727_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccontract',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='status',
            field=models.CharField(choices=[('outstanding', 'outstanding'), ('in_progress', 'in_progress'), ('finished_issuer', 'finished_issuer'), ('finished_contractor', 'finished_contractor'), ('finished', 'finished'), ('cancelled', 'cancelled'), ('rejected', 'rejected'), ('failed', 'failed'), ('deleted', 'deleted'), ('reversed', 'reversed')], default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='title',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=30, null=True),
        ),
    ]
