# Generated by Django 2.2.2 on 2019-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0042_auto_20190727_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccontract',
            name='contract_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='date_issued',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='for_corporation',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='issuer_corporation_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontract',
            name='issuer_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
