# Generated by Django 2.2.2 on 2019-07-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0043_auto_20190727_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccontractitem',
            name='included',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontractitem',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontractitem',
            name='record_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontractitem',
            name='singleton',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publiccontractitem',
            name='type_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
