# Generated by Django 2.2.2 on 2019-07-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0044_auto_20190727_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccontract',
            name='acceptor_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptor', to='alliancetools.EveName'),
        ),
        migrations.AddField(
            model_name='publiccontract',
            name='assignee_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to='alliancetools.EveName'),
        ),
        migrations.AddField(
            model_name='publiccontract',
            name='issuer_corporation_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuer_corp', to='alliancetools.EveName'),
        ),
        migrations.AddField(
            model_name='publiccontract',
            name='issuer_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuer', to='alliancetools.EveName'),
        ),
        migrations.AddField(
            model_name='publiccontract',
            name='start_location_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_name', to='alliancetools.Structure'),
        ),
        migrations.AddField(
            model_name='publiccontractitem',
            name='type_name',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
