# Generated by Django 2.2.2 on 2019-07-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0045_auto_20190728_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiccontractitem',
            name='type_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alliancetools.TypeName'),
        ),
    ]
