# Generated by Django 2.2.2 on 2019-08-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0046_auto_20190728_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_hash', models.CharField(default=None, max_length=255, null=True, unique=True)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField(default=None, null=True)),
                ('date_accessed', models.DateTimeField(auto_now=True)),
                ('apikey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.ApiKey')),
            ],
        ),
    ]
