# Generated by Django 2.2.2 on 2019-08-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0047_apikey_apikeylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.BigIntegerField(default=None, null=True)),
                ('character', models.CharField(default=None, max_length=255, null=True)),
                ('corporation', models.CharField(default=None, max_length=255, null=True)),
                ('profession_isk', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('profession_count', models.IntegerField(default=None, null=True)),
                ('moon_isk', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('moon_count', models.IntegerField(default=None, null=True)),
                ('sum_isk', models.DecimalField(decimal_places=2, default=None, max_digits=20, null=True)),
                ('personal_id', models.CharField(default=None, max_length=255, null=True)),
                ('transaction_id', models.CharField(default=None, max_length=255, null=True)),
                ('professions', models.TextField(default=None, null=True)),
                ('moons', models.TextField(default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
