# Generated by Django 2.2.2 on 2019-08-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0049_auto_20190820_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliancecontact',
            name='contact_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.EveName'),
        ),
        migrations.AddField(
            model_name='corporatecontact',
            name='contact_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.EveName'),
        ),
    ]
