# Generated by Django 2.2.2 on 2019-08-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0050_auto_20190820_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructurePaymentCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now=True)),
                ('structure_id', models.BigIntegerField()),
                ('completed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCharacter')),
            ],
        ),
    ]
