# Generated by Django 2.2.2 on 2019-08-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0051_structurepaymentcompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelNotifierFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_webhook', models.TextField()),
                ('struct_filter_exclude', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('struct_filter_include', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('ping_citadel_levels', models.BooleanField(default=True)),
                ('ping_engineering_levels', models.BooleanField(default=True)),
                ('ping_refinary_levels', models.BooleanField(default=True)),
                ('ping_flex_levels', models.BooleanField(default=True)),
                ('ping_flex_ozone_levels', models.BooleanField(default=True)),
                ('corporation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCorporationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lo_ping', models.BooleanField(default=False)),
                ('lo_level', models.IntegerField(blank=True, default=None, null=True)),
                ('last_ping_lo_level', models.IntegerField(blank=True, default=None, null=True)),
                ('date_empty', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_ping_time', models.IntegerField(blank=True, default=None, null=True)),
                ('last_message', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.FuelNotifierFilter')),
                ('structure', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='alliancetools.Structure')),
            ],
        ),
    ]
