# Generated by Django 2.2.2 on 2019-09-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0054_miningobservation_observing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningobserver',
            name='closest_celestial',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.StructureCelestial'),
        ),
        migrations.AddField(
            model_name='miningobserver',
            name='observer_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miningobserver',
            name='system_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alliancetools.MapSolarSystem'),
        ),
    ]
