# Generated by Django 2.2.2 on 2019-09-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0055_auto_20190905_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('region', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('constellation', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('system', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('moon', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
            ],
        ),
    ]
