# Generated by Django 2.2.2 on 2019-09-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alliancetools', '0056_miningtax'),
    ]

    operations = [
        migrations.AddField(
            model_name='evename',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
