# Generated by Django 2.2.2 on 2019-10-02 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        ('alliancetools', '0057_evename_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('duration', models.IntegerField(default=48)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliancetools.Structure')),
            ],
        ),
    ]
